apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: ecommerce-stage
  labels:
    app: shipping-service
    environment: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
        environment: stage
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: shipping-service
        image: rojas43529/shipping-service:stage-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8600
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          value: "false"
        envFrom:
        - configMapRef:
            name: microservices-config
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8600
          initialDelaySeconds: 45
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8600
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: ecommerce-stage
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
  - port: 8600
    targetPort: 8600
    name: http
  type: ClusterIP
