apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce-dev
  labels:
    app: payment-service
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        environment: dev
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: payment-service
        image: rojas43529/payment-service:dev-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8400
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_CLOUD_DISCOVERY_ENABLED
          value: "false"
        envFrom:
        - configMapRef:
            name: microservices-config
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8400
          initialDelaySeconds: 45
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8400
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce-dev
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8400
    targetPort: 8400
    name: http
  type: ClusterIP
