// Declarative Jenkins pipeline for shipping-service (Dev pipeline)
pipeline {
  agent any

  environment {
    MAVEN_OPTS = '-Xmx1024m'
    IMAGE_NAME = 'shipping-service'
    DOCKER_REGISTRY = ''
    DOCKER_CREDENTIALS_ID = 'docker-registry-credentials'
    PUBLISH = 'false'
  }

  options {
    timestamps()
    ansiColor('xterm')
    timeout(time: 60, unit: 'MINUTES')
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build & Unit Tests') {
      steps {
        echo 'Running Maven build and unit tests'
        sh 'mvn -B -V -U -DskipTests=false clean package'
      }
    }

    stage('Archive Artifact') {
      steps { archiveArtifacts artifacts: 'target/*.jar,target/*.jar.original', fingerprint: true, allowEmptyArchive: true }
    }
  }

  post {
    always {
      junit '**/target/surefire-reports/*.xml'
      archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
    }
  }
}
